---
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - windows-2019
          - windows-2016
        perl: ['5.32', '5.30', '5.28', '5.22']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Platform check
        run: uname -a
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: |
          cpanm -iqn --skip-satisfied warnings::unused B::Lint Geo::Coder::Abbreviations Class::Simple
      - name: Run Tests
        run: |
          perl -MO=Lint NJH/PDFPage.pm
          perl -c -Mwarnings::unused NJH/PDFPage.pm
          perl -MO=Lint NJH/Normalize.pm
          perl -c -Mwarnings::unused NJH/Normalize.pm
          perl -MO=Lint NJH/Place.pm
          perl -c -Mwarnings::unused NJH/Place.pm
